name = "sy21"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

pages_build_output_dir = ".vercel/output/static"

[[kv_namespaces]]
binding = "CKTV_SEARCH_CACHE"
id = "fcbae0c73d764a629395553970940754"

[ai]
binding = "AI"

[[crons]]
cron = "0 * * * *"

[vars]
DAILY_FREE_NEURONS = "10000"
ENABLE_PAID = "false"
