name = "ck-tv"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

pages_build_output_dir = ".vercel/output/static"

[ai]
binding = "AI"

[vars]
DAILY_FREE_NEURONS = "10000"
ENABLE_PAID = "false"
